### ISSUE TITLE
Behaviour

### ISSUE THREAD

**Issue by Baptouuuu** [Innmind/ProvisionerBundle#1]
This issue is here to explain how the bundle works internally, and open it for discussion.
## Behaviour
- When a consumer is killed (it has finished consuming `x` messages), the provisioner is launched
- It looks how many messages still in the queue and compare it to the last time it checked
  - if new number is higher, it will launch `x` consumers (diff of messages number divided by number of messages a consumer will read)
  - if new number is lower, launch only one consumer. If the number is lower than the number of messages consumed by the consumer it not launch a new consumer if one already started.
## Resource restriction
- you can specify a CPU max threshold
  - if the provisioner needs to launch more consumer but has reached this threshold, it will alert you to run a new server. A event will be fired so you could add some code to automate the creation of new servers.
- you can specify a CPU min threshold
  - when the provisioner is started but see it doesn't need to launch new consumers and the CPU is lower than this threshold, it will alert you that you may not need this server anymore
## Alerting

The alert will contain how many consumers needs to be launched and how many are currently launched on the server.

**Comment by luxifer** [comment]
This command would have to be launched by a cron task?

What about the memory. Sometimes, for workers used to crop pictures it would consume a lot of memory. What about trigerring events like for the CPU?

**Comment by Baptouuuu** [comment]
It will be launched when `console.terminate` is fired.

For pictures, the number of messages consumed should be low, say 2 or 3. In this case the provisioner will reuse the number of messages specified when you launched the first consumer.

Events will be standard symfony events, I don't know yet what or how much informations it will hold.

**Comment by luxifer** [comment]
Sounds great :smile: 

I think it should be able to handle webhook in addition to the mail notification and also chat notification such as hipchat or slack

**Comment by Baptouuuu** [comment]
Yep I also had the webhook in mind :)

Good idea the chat notification, not the priority though
